### ISSUE TITLE
Fix Google Maps.

### ISSUE THREAD

**Issue by ltrainpr** [colorado-code-for-communities/androidtracks#1]
Fix Google Maps.

**Comment by MikeLockz** [comment]
Followed instructions to add references to local libraries and receive error:

06-18 23:36:35.953: E/Google Maps Android API(25581): Failed to load map. Error contacting Google servers. This is probably an authentication issue (but could be due to network errors).

**Comment by MikeLockz** [comment]
Application SHA-1 hash wasn't in Google API Developer Console. Added hash to Google resolved issue. 37e494154906754d2fc88c35a580042b04d814c9
