### ISSUE TITLE
Use ISO8601 Dates when uploading trips

### ISSUE THREAD

**Issue by sduckett** [colorado-code-for-communities/androidtracks#13]
The current behavior is to use a date format of "yyyy-MM-dd HH:mm:ss".

By using ISO8601, as "yyyy-MM-dd'T'HH:mm:ssZ", parsing the encoded/decoded JSON object for analysis is much easier.

Better to simplify the problem early on, yes?

**Comment by apryce** [comment]
I'll look into this issue.
